server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.today/fireBird
    username: fireBird
    password: fireBird
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/thymeleaf-springboot/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  web:
    resources:
      static-locations: C:/thymeleaf-springboot/

## MAC용 url
#img:
#  macurl: /Users/theakim/Desktop/dev/04_Project/bread/breadImages/

# 이미지 저장할 위치와 응답 시 이미지 주소 설정
img:
  # WebConfig에 세팅
  add-resource-locations: file:////productimgs/
  add-resource-handler: /productimgs/**
  # ProductService에 세팅
  image-dir: /Users/theakim/Desktop/dev/04_Project/bread/breadImages/
  macurl: /Users/theakim/Desktop/dev/04_Project/bread/breadImages/

mybatis:
#  # mapper.xml location Setting
  mapper-locations: mappers/**/*.xml
#  # alias Setting
#  type-aliases-package: com.fireBird.breadUniv
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info